name: Main Workflow
on: [workflow_dispatch,push,pull_request]
  #
jobs:
  call-reusable-workflow:
    uses: ugcity/reuseable-flows/.github/workflows/reuseable-flow.yml@main
    with:
      node-version: '18'
      npm-install-command: 'ci'
      run-playwright: true
      upload-artifact: true
