name: Playwright Tests
on:
  workflow_dispatch:
    inputs:
      node-version:
        description: "Node.js version"
        required: false
        default: "14.x" # Default Node.js version if not provided
      npm-install-command:
        description: "npm install command"
        required: true
      run-playwright:
        description: "Enable Playwright testing"
        required: false
        default: "true" # Enable Playwright testing by default
      upload-artifact:
        description: "Enable artifact upload"
        required: false
        default: "true" # Enable artifact upload by default
  # push:
  #   branches: [main, master]
  # pull_request:
  #   branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install dependencies
        run: npm ${{ inputs.npm-install-command }}

      - name: Install Playwright Browsers
        if: ${{ inputs.run-playwright == 'true' }}
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        if: ${{ inputs.run-playwright == 'true' }}
        run: npx playwright test
        env:
          USERNAME: ${{secrets.USERNAME}}
          PASSWORD: ${{secrets.PASSWORD}}
      - uses: actions/upload-artifact@v3
        if: ${{ inputs.upload-artifact == 'true' }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
